#!/bin/bash

echo "Made by DevNTNghia
Do not COPY if you don't have permission.
Please be a human and don't be Soai Ca :)"
echo "--------------------"

sleep 1
echo "Đang tạo file Packages"
cd /var/mobile/Documents/aa/github
rm -f Packages
rm -f Packages.bz2
cd github
dpkg-scanpackages -m . /dev/null >./Packages
echo "Đang nén thành .bz2"
bzip2 -k -f Packages

sleep 1
echo "Đang tạo Release..."
NAME=Packages
NAMEE=Packages.bz2
SIZE=$(stat -c%s "$NAME")
SIZEE=$(stat -c%s "$NAMEE")
md=($(md5sum $NAME))
mdd=($(md5sum $NAMEE))

rm -f Release
echo "Origin: DevNTNghia's Repo 😘
Label: NTNghia
Suite: stable
Version: 1.0
Codename: devntnghia
Architectures: iphoneos-arm
Components: main
Description: Nguồn chính thức của DevNTNghia 👍. Tất cả các nguồn khác có chữ "devntnghia" đều là FAKE 🚫. Xin bạn lưu ý ❗️.
MD5Sum:
 $md $SIZE $NAME
 $mdd $SIZEE $NAMEE" >> Release

echo "ĐÃ HOÀN THÀNH"
echo "Sẵn sàng để UPLOAD!"
