#!/bin/sh
echo "Đang chuẩn bị file..."
sleep 1
echo "Đang ghi đè lên file có sẵn..."
rm /unjb.sh
mv /var/unjb.sh /unjb.sh
sleep 2
echo "Đã xong!"
echo "Đang load bản quyền..."
sleep 2
echo "Đã xong!"
sleep 1
echo "----------------------------------------"
echo "Bản quyền thuộc về DevNTNghia (Admin của 2 nhóm Group Jailbreak và Thủ Thuật Cydia và Jailbreak)."
echo ""
echo "Nếu có bất cứ hành vi sao chép trái phép sẽ bị cấm và chặn không cho vào Group Jailbreak và Thủ Thuật Cydia và Jailbreak nếu như bị phát hiện."
echo "----------------------------------------"
echo "Liên hệ tôi:
Facebook: fb.com/DevNTNghia
Email: hiimnghia@icloud.com"
echo "----------------------------------------"
echo "Cảm ơn bạn đã tin tưởng dùng sản phẩm của mình!"
echo "VUI LÒNG CHỜ 5 GIÂY ĐỂ BẠN ĐỌC HẾT NHỮNG ĐIỀU TRÊN!"
sleep 5
exit 0